CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_SDMMC_STACK=y
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y
CONFIG_I2S=y
CONFIG_I2S_NRFX=y
CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=6144
CONFIG_HEAP_MEM_POOL_SIZE=8192
