M48
; DRILL file {KiCad 9.0.7} date 2026-05-11T11:54:19+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-11T11:54:19+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X103.537Y-53.148
X111.537Y-53.134
T2
X125.0Y-73.1
X131.8Y-73.1
T3
X116.7Y-64.062
X116.7Y-71.062
T4
X91.4Y-33.4
X91.8Y-67.2
X128.8Y-65.7
X129.8Y-32.9
M30
