CONFIG_STDOUT_CONSOLE=n # Turned OFF. Direct satandard output to the console, which is useful for debugging and logging purposes.

# CONFIG_LOG_MODE_IMMEDIATE=y # Forces the logger to output log messages immediately instead of buffering them. This is useful for real-time debugging, but may have performance implications.
# CONFIG_PWM_LOG_LEVEL_DBG=y # To see every internal detail of the PWM driver, set the log level to debug. This will provide detailed information about the PWM operations, which can be helpful for troubleshooting and understanding how the driver works.
# CONFIG_LOG_DEFAULT_LEVEL=3 # Set the default log level to "Info". This means that only informational messages, warnings, and errors will be logged, while debug messages will be ignored. This is a common setting for production code to reduce log verbosity while still capturing important information.

# Use the internal RC oscillator instead of an external crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION=y  # Callibrates the internal RC oscillator to improve accuracy, which is important for timing-sensitive applications like PWM and SD card communication.

# NCS forces CONFIG_NRF_APPROTECT_USE_UICR=y (reads UICR.APPROTECT on boot).
# The application now updates UICR.REGOUT0 at boot when it needs to move the
# REG0 output to 3.0 V.

# Configurations for the SD Card
CONFIG_SPI=y         # Enables the SPI driver, which is necessary for communicating with the SD card over the SPI interface.
CONFIG_GPIO=y        # Enables the GPIO driver, which is needed to control the chip select pin for the SD card and to detect card insertion/removal if necessary.
CONFIG_SDHC=y        # Enables the SD Host Controller driver, which allows the CPU to talk to SD cards using the SDHC interface.
CONFIG_PWM=y         # Enables the PWM driver, which is used to control the brightness of the LED based on the SD card status.
CONFIG_GPIO_NRFX=y   # Enables interrupt support for GPIO

# Provides a high-level API to access storage devices as raw blocks of data. This is used by the FAT file system to read and write files on the SD card.
CONFIG_DISK_ACCESS=y 
# Compiles the actual drivers that manage disk-type hardware
CONFIG_DISK_DRIVERS=y

# Enables generic file system layer (VFS) support
CONFIG_FILE_SYSTEM=y
# Adds the ability to format a disk (make a file system) directly from code
CONFIG_FILE_SYSTEM_MKFS=y
# Includes the "ELM FastFs" library, which is the industry standard for FAT filesystems on microcontrollers
CONFIG_FAT_FILESYSTEM_ELM=y
# Automatically mounts the SD card when the system boots up, based on a defined table. Part of DeviceTree, Not kconfig. Without defining in DT this will throw an error.  
CONFIG_FS_FATFS_FSTAB_AUTOMOUNT=y
# Defining maximum number of files we can simulateously have open. This is important for resource management, especially on embedded systems with limited memory.
# CONFIG_FS_FATFS_NUM_FILES=4

#System & Debugging
# Sets memory allocated to main thread
# Size of Main Stack
CONFIG_MAIN_STACK_SIZE=4096
# Size of Heap Memory Pool
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_LOG=n                  # Turns OFF logging system
# CONFIG_LOG_MODE_MINIMAL=y   # Stripped down version of the logger to save flash memory and RAM. 

# Configuring audio settings
# Master switch which enables general audio subsystem framework.
CONFIG_AUDIO=y
# Enabling Digital Microphone hardware driver
CONFIG_AUDIO_DMIC=y

# Turning USB-to-Serial port into an interactive CLI
# CONFIG_SHELL=y
# CONFIG_SHELL_BACKEND_SERIAL=y
# CONFIG_UART_CONSOLE=y

# Enable I2S driver
CONFIG_I2S=y
CONFIG_I2S_NRFX=y
CONFIG_DMA=y
CONFIG_CLOCK_CONTROL_NRF=y
